drop table if exists hist_inst_cache_transfer
\g

create table hist_inst_cache_transfer (
  snap_id bigint not null,
  instance_number int not null,
  startup_time datetime not null,
  instance int not null,
  class varchar(18) not null,
  old_cr_block double not null,
  dif_cr_block double not null,
  old_cr_busy double not null,
  dif_cr_busy double not null,
  old_cr_congested double not null,
  dif_cr_congested double not null,
  old_current_block double not null,
  dif_current_block double not null,
  old_current_busy double not null,
  dif_current_busy double not null,
  old_current_congested double not null,
  dif_current_congested double not null,
  old_lost double not null,
  dif_lost double not null,
  old_cr_block_time double not null,
  dif_cr_block_time double not null,
  old_cr_busy_time double not null,
  dif_cr_busy_time double not null,
  old_cr_congested_time double not null,
  dif_cr_congested_time double not null,
  old_current_block_time double not null,
  dif_current_block_time double not null,
  old_current_busy_time double not null,
  dif_current_busy_time double not null,
  old_current_congested_time double not null,
  dif_current_congested_time double not null,
  old_lost_time double not null,
  dif_lost_time double not null,
  end_interval_time datetime not null,
  dif_interval varchar(32) not null,
  dummy1 varchar(80),
  con_dbid bigint,
  con_id int,
  dummy2 varchar(80),
  dif_sec double not null
)
\g
exit
