drop table if exists hist_seg_stat
\g

create table hist_seg_stat (
  snap_id bigint not null,
  db_id bigint not null,
  instance_number int not null,
  startup_time datetime not null,
  ts_id int not null,
  obj_id bigint not null, 
  dataobj_id bigint not null, 
  logical_reads_total double not null,
  logical_reads_delta double not null,
  buffer_busy_waits_total double not null,
  buffer_busy_waits_delta double not null,
  db_block_chages_total double not null,
  db_block_chages_delta double not null,
  physical_reads_total double not null,
  physical_reads_delta double not null,
  physical_writes_total double not null,
  physical_writes_delta double not null,
  physical_reads_direct_total double not null,
  physical_reads_direct_delta double not null,
  physical_writes_direct_total double not null,
  physical_writes_direct_delta double not null,
  itl_waits_total double not null,
  itl_waits_delta double not null,
  row_lock_waits_total double not null,
  row_lock_waits_delta double not null,
  gc_cr_blocks_served_total double not null,
  gc_cr_blocks_served_delta double not null,
  gc_cu_blocks_served_total double not null,
  gc_cu_blocks_served_delta double not null,
  gc_buffer_busy_total double not null,
  gc_buffer_busy_delta double not null,
  gc_cr_blocks_received_total double not null,
  gc_cr_blocks_received_delta double not null,
  gc_cu_blocks_received_total double not null,
  gc_cu_blocks_received_delta double not null,
  space_used_total double not null,
  space_used_delta double not null,
  space_allocated_total double not null,
  space_allocated_delta double not null,
  table_scans_total double not null,
  table_scans_delta double not null,
  physical_read_requests_total double not null,
  physical_read_requests_delta double not null,
  physical_write_requests_total double not null,
  physical_write_requests_delta double not null,
  optimized_physical_reads_total double not null,
  optimized_physical_reads_delta double not null,
  end_interval_time datetime not null,
  dif_interval varchar(32) not null,
  dummy1 varchar(80),
  con_dbid bigint,
  con_id int,
  dummy2 varchar(80),
  dif_sec double not null
)
\g
exit
