.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "AGRAF_EXPORT" "7" "September 2020" "" ""
.
.SH "NAME"
\fBagraf_export\fR \- export data from AWR to CSV files
.
.SH "SYNOPSIS"
\fBagraf_export\.py\fR [\fIargs\fR]
.
.SH "DESCRIPTION"
agraf_export(7) exports performance data from the local Oracle database\. The performance statistics are written into the CSV files\. You can choose to export AWR and ADDM reports as well\. You have to specify the output directory, time interval and export types\. The export is done by running SQL statements from the SQL*Plus with SYS user:
.
.P
\fBsqlplus / as sysdba\fR
.
.P
No SQL statements are exported directly from the AWR\. If you want to provide the SQL statements, you have to export the AWR reports in HTML format using the \fB\-a\fR option\.
.
.P
After downloading the agraf_export\.tar\.gz, you have to tranfer it to the database server\. You should unpack it in a new directory and create a new output directory\. The Python script can be started from the unpacked oracle directory\. So the usual steps are: * mkdir output * tar zxvf \./agraf_export\.tar\.gz * cd oracle * \./agraf_export\.py \-output_dir \.\./output \.\.\.
.
.P
At the end of export one or many gzipped tar files will be created\. Only these files should be uploaded for further processing\.
.
.SH "OPTIONS:"
agraf_export\.py \-\-begin_time TimeStamp \-\-end_time TimeStamp \-\-output_dir Directory [\-\-all
.
.br
\-\-format FormatTypes \-\-parallel Number \-\-reports ReportTypes \-\-components {seg|noseg} \-\-instance_id Number \-\-summary \-\-summary_only \-\-sql_id SQL_IDs \-\-min_snap_id Number \-\-max_snap_id Number \-\-verbose]
.
.IP "\(bu" 4
\fB{\-b | \-\-begin_time}\fR \fITimeStamp\fR: Export begin time\. The possible formats are {yyyy\-mm\-dd hh24:mi | yyyy\-mm\-dd | hh24\-mi}\.
.
.IP "\(bu" 4
\fB{\-e | \-\-end_time}\fR \fITimeStamp\fR: Export end time\. The possible formats are {yyyy\-mm\-dd hh24:mi | yyyy\-mm\-dd | hh24\-mi | now}\.
.
.IP "\(bu" 4
\fB{\-o | \-\-output_dir}\fR \fIDirectory\fR: Export output directory\.
.
.IP "\(bu" 4
\fB{\-a | \-\-all}\fR: Export both data and AWR/ADDM reports\.
.
.IP "\(bu" 4
\fB{\-f | \-\-format}\fR \fIFormatTypes\fR: AWR and ADDM report formats {text, html, active\-html}
.
.IP "\(bu" 4
\fB{\-p | \-\-parallel}\fR \fINumber\fR: Number of parallel sessions to generate the AWR and ADDM reports\.
.
.IP "\(bu" 4
\fB{\-r | \-\-reports}\fR \fIReportTypes\fR: Possible reports are
.
.br
{nodata | AWR | ADDM | SQL | SQLTEXT}\.
.
.IP "\(bu" 4
\fB{\-c | \-\-components}\fR \fI{seg|noseg}\fR: Should segment statistics be exported? The default is no, because of possible high amount of data\.
.
.IP "\(bu" 4
\fB{\-i | \-\-instance_id}\fR \fIInstanceID\fR : Export should be done only for the specified instance ID\.
.
.IP "\(bu" 4
\fB{\-\-summary}\fR : Summary reports between the first and the last snapshot IDs should be created\.
.
.IP "\(bu" 4
\fB{\-\-summary_only}\fR : Only summary reports should be created\.
.
.IP "\(bu" 4
\fB{\-s | \-sql_id}\fR \fISQL_IDs\fR: Generate AWR SQL reports for the specified SQL_IDs\.
.
.IP "\(bu" 4
\fB{\-n | \-\-min_snap_id}\fR \fISnapID\fR: Specify the begin interval as a snapshot ID\.
.
.IP "\(bu" 4
\fB{\-x | \-\-max_snap_id}\fR \fISnapID\fR: Specify the end interval as a snapshot ID\.
.
.IP "" 0
.
.SH "EXAMPLES"
In most cases the following options shoud be used:
.
.P
\fB\./agraf_export\.py \-b "2020\-08\-20 21:00" \-e "2020\-08\-21 23:00" \-a \-o \.\./output\fR
.
.P
Export the statistics data from AWR for the specified time interval\. The output directory is \fB\.\./output\fR\. The \fB\-a\fR option generates AWR and ADDM reports\.
.
.P
\fB\./agraf_export\.py \-b "2020\-08\-20 21:00" \-e "2020\-08\-21 23:00" \-r nodata,sqltext \-o \.\./output\fR
.
.P
Per default SQL statements are not exported\. The \fBsqltext\fR report type option generates SQL statements into the text file\. You need \fBstmt2agraf\fR program to import these SQL statements into the MySQL database\.
.
.P
\fB\./agraf_export\.py \-b "2020\-08\-20 21:00" \-e "2020\-08\-21 23:00" \-a \-r sqltext \-o \.\./output\fR
.
.P
Export AGRAF data together with SQL statements and AWR/ADDM reports\.
.
.P
\fBagraf_export\.py \-\-begin_time "2019\-01\-14" \-\-end_time now \-o ~/tmp/output \-a \-\-parallel 4 \-\-summary\fR
.
.P
Export data between the specified start time and now\. The AWR/ADDM reports will be generated as well\. These reports will be generated in parallel with max parallel degree of 4\. Because of the \fB\-\-summary\fR option additionally AWR/ADDM reports for the whole interval will be generated\.
.
.P
\fBagraf_export\.py \-\-min_snap_id 310 \-max_snap_id 314 \-o ~/tmp/output \-\-report nodata,sql \-s 7z63yy1hazt9s,1uk5m5qbzj1vt \-\-summary_only\fR
.
.P
Generate AWR SQL reports for the specified SQL_IDs\. Because of the \fB\-\-summary_only\fR option, only one SQL report for the whole AWR interval between min and max snapshot IDs will be created\.
.
.SH "AUTHOR"
Andrej Simon \fIandrej\.simon@oracle\.com\fR
.
.SH "SEE ALSO"
agraf_import(7) stmt2agraf(7)
.
.P
AGRAF \fIhttps://github\.com/asimondev/agraf\fR
